# Generated by Django 3.2.4 on 2022-03-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20220228_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='latestMessageId',
            new_name='latestUser1ReadId',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='latestReadId',
            new_name='latestUser2ReadId',
        ),
    ]
