# Generated by Django 3.2.4 on 2022-03-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0004_message_isread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='latestUser1ReadId',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='latestUser2ReadId',
        ),
    ]
