# Generated by Django 3.2.4 on 2022-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0005_auto_20220228_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(db_column='userIds', related_name='_messenger_backend_conversationgroup_users_+', to='messenger_backend.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
